# Spring properties
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/test
  application:
    name: user-service  # Service registers under this name

endpoints:
  health:
    enabled: true
  shutdown:
    enabled: true

management:
    context-path: /admin
logging:
  level:
    org:
      springframework:
        web:
          client: DEBUG

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port

